# Generated by Django 6.0.3 on 2026-03-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=200)),
                ('idea_description', models.TextField()),
                ('idea_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
